import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  playlist: [
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist1',
      slug: 'playlist-1',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-2',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-3',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-4',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-5',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-6',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-7',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-8',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-9',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-10',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-11',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-12',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-13',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-14',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'playlist2',
      slug: 'playlist-15',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      type: 'video',
      description: 'A popular shirt',
    },
  ],
  products: [
    {
      user: '613f3c0b217785ee9b399d9c',
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
}
export default data
